list_buah = ['Duren', 'Jambu', 'Pisang', 'Apel']
print('list_buah',list_buah)
print(list_buah[0])
print(list_buah[1])
print(list_buah[2])
print(list_buah[3])
print(list_buah[1:3])
list_buah[0] = 'pepaya'
print(list_buah)
list_buah.append('mangga')
print(list_buah)
list_buah.insert(0,'duren')
print(list_buah)
list_buah.insert(3,'anggur')
print(list_buah)
list_buah.remove('anggur')
print(list_buah)
list_buah.pop()
print(list_buah)
del list_buah[0]
print(list_buah)
list_buah.append('Jeruk')
print(list_buah)
list_buah.sort()
print(list_buah)